apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8sgrpcsv
spec:
  template:
    spec:
      containers:
      - name: k8sgrpcsv
        env:
        - name: PROJECT_ENV
          value: "dev"