// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CheckTokenReq struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Type                 int32    `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckTokenReq) Reset()         { *m = CheckTokenReq{} }
func (m *CheckTokenReq) String() string { return proto.CompactTextString(m) }
func (*CheckTokenReq) ProtoMessage()    {}
func (*CheckTokenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *CheckTokenReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckTokenReq.Unmarshal(m, b)
}
func (m *CheckTokenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckTokenReq.Marshal(b, m, deterministic)
}
func (m *CheckTokenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckTokenReq.Merge(m, src)
}
func (m *CheckTokenReq) XXX_Size() int {
	return xxx_messageInfo_CheckTokenReq.Size(m)
}
func (m *CheckTokenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckTokenReq.DiscardUnknown(m)
}

var xxx_messageInfo_CheckTokenReq proto.InternalMessageInfo

func (m *CheckTokenReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *CheckTokenReq) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

type CheckTokenResp struct {
	Code                 int32             `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 map[string]string `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CheckTokenResp) Reset()         { *m = CheckTokenResp{} }
func (m *CheckTokenResp) String() string { return proto.CompactTextString(m) }
func (*CheckTokenResp) ProtoMessage()    {}
func (*CheckTokenResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *CheckTokenResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckTokenResp.Unmarshal(m, b)
}
func (m *CheckTokenResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckTokenResp.Marshal(b, m, deterministic)
}
func (m *CheckTokenResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckTokenResp.Merge(m, src)
}
func (m *CheckTokenResp) XXX_Size() int {
	return xxx_messageInfo_CheckTokenResp.Size(m)
}
func (m *CheckTokenResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckTokenResp.DiscardUnknown(m)
}

var xxx_messageInfo_CheckTokenResp proto.InternalMessageInfo

func (m *CheckTokenResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CheckTokenResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CheckTokenResp) GetData() map[string]string {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*CheckTokenReq)(nil), "user.CheckTokenReq")
	proto.RegisterType((*CheckTokenResp)(nil), "user.CheckTokenResp")
	proto.RegisterMapType((map[string]string)(nil), "user.CheckTokenResp.DataEntry")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 227 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xcd, 0x4e, 0x84, 0x30,
	0x14, 0x85, 0xd3, 0x01, 0x34, 0xdc, 0x89, 0xc6, 0x5c, 0x67, 0xd1, 0xcc, 0xc2, 0x90, 0x59, 0xb1,
	0x62, 0x81, 0x0b, 0xd4, 0xad, 0xe8, 0x03, 0x54, 0x5f, 0xa0, 0xc2, 0x8d, 0x1a, 0x84, 0x42, 0x5b,
	0x48, 0x78, 0x26, 0x5f, 0xd2, 0xb4, 0x88, 0x3f, 0xd1, 0xdd, 0x77, 0x9a, 0x73, 0x7a, 0x4e, 0x2e,
	0xc0, 0x68, 0x48, 0x67, 0xbd, 0x56, 0x56, 0x61, 0xe8, 0xf8, 0x70, 0x0d, 0x27, 0xb7, 0x2f, 0x54,
	0x35, 0x8f, 0xaa, 0xa1, 0x4e, 0xd0, 0x80, 0x3b, 0x88, 0xac, 0x63, 0xce, 0x12, 0x96, 0xc6, 0x62,
	0x11, 0x88, 0x10, 0xda, 0xb9, 0x27, 0xbe, 0x49, 0x58, 0x1a, 0x09, 0xcf, 0x87, 0x77, 0x06, 0xa7,
	0x3f, 0xb3, 0xa6, 0x77, 0xb6, 0x4a, 0xd5, 0xe4, 0xb3, 0x91, 0xf0, 0x8c, 0x1c, 0x8e, 0x5b, 0x32,
	0x46, 0x3e, 0x2f, 0xe9, 0x58, 0xac, 0x12, 0x73, 0x08, 0x6b, 0x69, 0x25, 0x0f, 0x92, 0x20, 0xdd,
	0xe6, 0x17, 0x99, 0x1f, 0xf7, 0xfb, 0xc7, 0xac, 0x94, 0x56, 0xde, 0x75, 0x56, 0xcf, 0xc2, 0x7b,
	0xf7, 0x05, 0xc4, 0x5f, 0x4f, 0x78, 0x06, 0x41, 0x43, 0xf3, 0xe7, 0x52, 0x87, 0x6e, 0xfd, 0x24,
	0xdf, 0xc6, 0xb5, 0x6a, 0x11, 0x37, 0x9b, 0x2b, 0x96, 0xdf, 0xc3, 0xb6, 0xa4, 0x56, 0x3d, 0x90,
	0x9e, 0x5e, 0x2b, 0xc2, 0x02, 0xe0, 0xbb, 0x09, 0xcf, 0xff, 0x76, 0x0f, 0xfb, 0xdd, 0x7f, 0x83,
	0x9e, 0x8e, 0xfc, 0xf5, 0x2e, 0x3f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x4d, 0x8c, 0x10, 0x58, 0x4b,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DemoServiceClient is the client API for DemoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DemoServiceClient interface {
	CheckToken(ctx context.Context, in *CheckTokenReq, opts ...grpc.CallOption) (*CheckTokenResp, error)
}

type demoServiceClient struct {
	cc *grpc.ClientConn
}

func NewDemoServiceClient(cc *grpc.ClientConn) DemoServiceClient {
	return &demoServiceClient{cc}
}

func (c *demoServiceClient) CheckToken(ctx context.Context, in *CheckTokenReq, opts ...grpc.CallOption) (*CheckTokenResp, error) {
	out := new(CheckTokenResp)
	err := c.cc.Invoke(ctx, "/user.DemoService/CheckToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DemoServiceServer is the server API for DemoService service.
type DemoServiceServer interface {
	CheckToken(context.Context, *CheckTokenReq) (*CheckTokenResp, error)
}

// UnimplementedDemoServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDemoServiceServer struct {
}

func (*UnimplementedDemoServiceServer) CheckToken(ctx context.Context, req *CheckTokenReq) (*CheckTokenResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckToken not implemented")
}

func RegisterDemoServiceServer(s *grpc.Server, srv DemoServiceServer) {
	s.RegisterService(&_DemoService_serviceDesc, srv)
}

func _DemoService_CheckToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckTokenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DemoServiceServer).CheckToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.DemoService/CheckToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DemoServiceServer).CheckToken(ctx, req.(*CheckTokenReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _DemoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.DemoService",
	HandlerType: (*DemoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckToken",
			Handler:    _DemoService_CheckToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
